import { Container } from "@/components/shared/Container";
import Image from "next/image";
export default function Home() {
  const data = {
    location: {
      name: "Posad Pazdelnaya",
      region: "Odes'ka Oblast'",
      country: "Ukraine",
      lat: 46.85,
      lon: 30.0833,
      tz_id: "Europe/Kiev",
      localtime_epoch: 1767609612,
      localtime: "2026-01-05 12:40",
    },
    current: {
      last_updated_epoch: 1767609000,
      last_updated: "2026-01-05 12:30",
      temp_c: 0.6,
      temp_f: 33.1,
      is_day: 1,
      condition: {
        text: "Помірний сніг",
        icon: "//cdn.weatherapi.com/weather/64x64/day/332.png",
        code: 1219,
      },
      wind_mph: 10.3,
      wind_kph: 16.6,
      wind_degree: 81,
      wind_dir: "E",
      pressure_mb: 1020,
      pressure_in: 30.13,
      precip_mm: 0.13,
      precip_in: 0.01,
      humidity: 88,
      cloud: 100,
      feelslike_c: -4,
      feelslike_f: 24.9,
      windchill_c: -4,
      windchill_f: 24.9,
      heatindex_c: 0.6,
      heatindex_f: 33,
      dewpoint_c: -1.1,
      dewpoint_f: 30,
      vis_km: 5,
      vis_miles: 3,
      uv: 0.2,
      gust_mph: 14,
      gust_kph: 22.6,
    },
    forecast: {
      forecastday: [
        {
          date: "2026-01-05",
          date_epoch: 1767571200,
          day: {
            maxtemp_c: 1.3,
            maxtemp_f: 34.4,
            mintemp_c: -0.2,
            mintemp_f: 31.7,
            avgtemp_c: 0.7,
            avgtemp_f: 33.3,
            maxwind_mph: 13.4,
            maxwind_kph: 21.6,
            totalprecip_mm: 1.74,
            totalprecip_in: 0.07,
            totalsnow_cm: 0.44,
            avgvis_km: 8.9,
            avgvis_miles: 5,
            avghumidity: 91,
            daily_will_it_rain: 1,
            daily_chance_of_rain: 92,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 15,
            condition: {
              text: "Помірний або сильний снігопад",
              icon: "//cdn.weatherapi.com/weather/64x64/day/371.png",
              code: 1258,
            },
            uv: 0,
          },
          astro: {
            sunrise: "07:45 AM",
            sunset: "04:25 PM",
            moonrise: "06:55 PM",
            moonset: "09:26 AM",
            moon_phase: "Waning Gibbous",
            moon_illumination: 96,
            is_moon_up: 1,
            is_sun_up: 0,
          },
          hour: [
            {
              time_epoch: 1767564000,
              time: "2026-01-05 00:00",
              temp_c: 0.2,
              temp_f: 32.4,
              is_day: 0,
              condition: {
                text: "Невелика хмарність",
                icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                code: 1003,
              },
              wind_mph: 8.1,
              wind_kph: 13,
              wind_degree: 330,
              wind_dir: "NNW",
              pressure_mb: 1015,
              pressure_in: 29.98,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 91,
              cloud: 51,
              feelslike_c: -3.7,
              feelslike_f: 25.3,
              windchill_c: -3.7,
              windchill_f: 25.3,
              heatindex_c: 0.2,
              heatindex_f: 32.4,
              dewpoint_c: -1.1,
              dewpoint_f: 30.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 13.2,
              gust_kph: 21.2,
              uv: 0,
            },
            {
              time_epoch: 1767567600,
              time: "2026-01-05 01:00",
              temp_c: -0.2,
              temp_f: 31.7,
              is_day: 0,
              condition: {
                text: "Суцільна хмарність",
                icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
                code: 1009,
              },
              wind_mph: 8.5,
              wind_kph: 13.7,
              wind_degree: 335,
              wind_dir: "NNW",
              pressure_mb: 1016,
              pressure_in: 30.01,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 89,
              cloud: 98,
              feelslike_c: -4.4,
              feelslike_f: 24.2,
              windchill_c: -4.4,
              windchill_f: 24.2,
              heatindex_c: -0.2,
              heatindex_f: 31.7,
              dewpoint_c: -1.8,
              dewpoint_f: 28.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.1,
              gust_kph: 22.7,
              uv: 0,
            },
            {
              time_epoch: 1767571200,
              time: "2026-01-05 02:00",
              temp_c: 0.2,
              temp_f: 32.4,
              is_day: 0,
              condition: {
                text: "Суцільна хмарність",
                icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
                code: 1009,
              },
              wind_mph: 8.1,
              wind_kph: 13,
              wind_degree: 353,
              wind_dir: "N",
              pressure_mb: 1017,
              pressure_in: 30.04,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 84,
              cloud: 100,
              feelslike_c: -3.8,
              feelslike_f: 25.2,
              windchill_c: -3.8,
              windchill_f: 25.2,
              heatindex_c: 0.2,
              heatindex_f: 32.4,
              dewpoint_c: -2.2,
              dewpoint_f: 28.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 12.4,
              gust_kph: 19.9,
              uv: 0,
            },
            {
              time_epoch: 1767574800,
              time: "2026-01-05 03:00",
              temp_c: 0.7,
              temp_f: 33.3,
              is_day: 0,
              condition: {
                text: "Суцільна хмарність",
                icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
                code: 1009,
              },
              wind_mph: 7.4,
              wind_kph: 11.9,
              wind_degree: 9,
              wind_dir: "N",
              pressure_mb: 1018,
              pressure_in: 30.07,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 83,
              cloud: 100,
              feelslike_c: -2.9,
              feelslike_f: 26.7,
              windchill_c: -2.9,
              windchill_f: 26.7,
              heatindex_c: 0.7,
              heatindex_f: 33.3,
              dewpoint_c: -1.9,
              dewpoint_f: 28.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 10,
              gust_kph: 16.1,
              uv: 0,
            },
            {
              time_epoch: 1767578400,
              time: "2026-01-05 04:00",
              temp_c: 0.5,
              temp_f: 32.9,
              is_day: 0,
              condition: {
                text: "Суцільна хмарність",
                icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
                code: 1009,
              },
              wind_mph: 6.9,
              wind_kph: 11.2,
              wind_degree: 30,
              wind_dir: "NNE",
              pressure_mb: 1019,
              pressure_in: 30.08,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 83,
              cloud: 100,
              feelslike_c: -3,
              feelslike_f: 26.6,
              windchill_c: -3,
              windchill_f: 26.6,
              heatindex_c: 0.5,
              heatindex_f: 32.9,
              dewpoint_c: -2,
              dewpoint_f: 28.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 9.3,
              gust_kph: 15,
              uv: 0,
            },
            {
              time_epoch: 1767582000,
              time: "2026-01-05 05:00",
              temp_c: 0.3,
              temp_f: 32.6,
              is_day: 0,
              condition: {
                text: "Суцільна хмарність",
                icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
                code: 1009,
              },
              wind_mph: 5.6,
              wind_kph: 9,
              wind_degree: 37,
              wind_dir: "NE",
              pressure_mb: 1019,
              pressure_in: 30.1,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 85,
              cloud: 100,
              feelslike_c: -2.6,
              feelslike_f: 27.2,
              windchill_c: -2.6,
              windchill_f: 27.2,
              heatindex_c: 0.3,
              heatindex_f: 32.6,
              dewpoint_c: -2,
              dewpoint_f: 28.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 7.6,
              gust_kph: 12.2,
              uv: 0,
            },
            {
              time_epoch: 1767585600,
              time: "2026-01-05 06:00",
              temp_c: 0.2,
              temp_f: 32.3,
              is_day: 0,
              condition: {
                text: "Суцільна хмарність",
                icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
                code: 1009,
              },
              wind_mph: 5.6,
              wind_kph: 9,
              wind_degree: 46,
              wind_dir: "NE",
              pressure_mb: 1020,
              pressure_in: 30.12,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 86,
              cloud: 100,
              feelslike_c: -2.8,
              feelslike_f: 26.9,
              windchill_c: -2.8,
              windchill_f: 26.9,
              heatindex_c: 0.2,
              heatindex_f: 32.3,
              dewpoint_c: -1.9,
              dewpoint_f: 28.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 7.7,
              gust_kph: 12.3,
              uv: 0,
            },
            {
              time_epoch: 1767589200,
              time: "2026-01-05 07:00",
              temp_c: -0.1,
              temp_f: 31.9,
              is_day: 0,
              condition: {
                text: "Суцільна хмарність",
                icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
                code: 1009,
              },
              wind_mph: 6.5,
              wind_kph: 10.4,
              wind_degree: 45,
              wind_dir: "NE",
              pressure_mb: 1020,
              pressure_in: 30.12,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 87,
              cloud: 100,
              feelslike_c: -3.5,
              feelslike_f: 25.7,
              windchill_c: -3.5,
              windchill_f: 25.7,
              heatindex_c: -0.1,
              heatindex_f: 31.9,
              dewpoint_c: -2,
              dewpoint_f: 28.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 9.2,
              gust_kph: 14.9,
              uv: 0,
            },
            {
              time_epoch: 1767592800,
              time: "2026-01-05 08:00",
              temp_c: -0.1,
              temp_f: 31.9,
              is_day: 1,
              condition: {
                text: "Суцільна хмарність",
                icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
                code: 1009,
              },
              wind_mph: 7.2,
              wind_kph: 11.5,
              wind_degree: 55,
              wind_dir: "NE",
              pressure_mb: 1020,
              pressure_in: 30.13,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 86,
              cloud: 100,
              feelslike_c: -3.8,
              feelslike_f: 25.2,
              windchill_c: -3.8,
              windchill_f: 25.2,
              heatindex_c: -0.1,
              heatindex_f: 31.9,
              dewpoint_c: -2.1,
              dewpoint_f: 28.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 10.2,
              gust_kph: 16.4,
              uv: 0,
            },
            {
              time_epoch: 1767596400,
              time: "2026-01-05 09:00",
              temp_c: 0.6,
              temp_f: 33,
              is_day: 1,
              condition: {
                text: "Невеликий сніг",
                icon: "//cdn.weatherapi.com/weather/64x64/day/326.png",
                code: 1213,
              },
              wind_mph: 8.3,
              wind_kph: 13.3,
              wind_degree: 70,
              wind_dir: "ENE",
              pressure_mb: 1021,
              pressure_in: 30.16,
              precip_mm: 0.02,
              precip_in: 0,
              snow_cm: 0.02,
              humidity: 83,
              cloud: 100,
              feelslike_c: -3.4,
              feelslike_f: 25.9,
              windchill_c: -3.4,
              windchill_f: 25.9,
              heatindex_c: 0.6,
              heatindex_f: 33,
              dewpoint_c: -2,
              dewpoint_f: 28.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 65,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 10.6,
              gust_kph: 17.1,
              uv: 0.1,
            },
            {
              time_epoch: 1767600000,
              time: "2026-01-05 10:00",
              temp_c: 1.1,
              temp_f: 33.9,
              is_day: 1,
              condition: {
                text: "Невеликий сніг",
                icon: "//cdn.weatherapi.com/weather/64x64/day/326.png",
                code: 1213,
              },
              wind_mph: 9.8,
              wind_kph: 15.8,
              wind_degree: 79,
              wind_dir: "E",
              pressure_mb: 1021,
              pressure_in: 30.16,
              precip_mm: 0.04,
              precip_in: 0,
              snow_cm: 0.03,
              humidity: 82,
              cloud: 100,
              feelslike_c: -3.3,
              feelslike_f: 26.2,
              windchill_c: -3.3,
              windchill_f: 26.2,
              heatindex_c: 1.1,
              heatindex_f: 33.9,
              dewpoint_c: -1.6,
              dewpoint_f: 29.1,
              will_it_rain: 1,
              chance_of_rain: 86,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 12,
              gust_kph: 19.3,
              uv: 0.2,
            },
            {
              time_epoch: 1767603600,
              time: "2026-01-05 11:00",
              temp_c: 0.9,
              temp_f: 33.7,
              is_day: 1,
              condition: {
                text: "Помірний сніг",
                icon: "//cdn.weatherapi.com/weather/64x64/day/332.png",
                code: 1219,
              },
              wind_mph: 9.4,
              wind_kph: 15.1,
              wind_degree: 79,
              wind_dir: "E",
              pressure_mb: 1021,
              pressure_in: 30.15,
              precip_mm: 0.08,
              precip_in: 0,
              snow_cm: 0.06,
              humidity: 84,
              cloud: 100,
              feelslike_c: -3.3,
              feelslike_f: 26.1,
              windchill_c: -3.3,
              windchill_f: 26.1,
              heatindex_c: 0.9,
              heatindex_f: 33.7,
              dewpoint_c: -1.5,
              dewpoint_f: 29.4,
              will_it_rain: 1,
              chance_of_rain: 100,
              will_it_snow: 0,
              chance_of_snow: 67,
              vis_km: 5,
              vis_miles: 3,
              gust_mph: 12.2,
              gust_kph: 19.7,
              uv: 0.2,
            },
            {
              time_epoch: 1767607200,
              time: "2026-01-05 12:00",
              temp_c: 0.6,
              temp_f: 33.1,
              is_day: 1,
              condition: {
                text: "Помірний сніг",
                icon: "//cdn.weatherapi.com/weather/64x64/day/332.png",
                code: 1219,
              },
              wind_mph: 10.3,
              wind_kph: 16.6,
              wind_degree: 81,
              wind_dir: "E",
              pressure_mb: 1020,
              pressure_in: 30.13,
              precip_mm: 0.13,
              precip_in: 0.01,
              snow_cm: 0.1,
              humidity: 88,
              cloud: 100,
              feelslike_c: -4,
              feelslike_f: 24.9,
              windchill_c: -4,
              windchill_f: 24.9,
              heatindex_c: 0.6,
              heatindex_f: 33,
              dewpoint_c: -1.1,
              dewpoint_f: 30,
              will_it_rain: 1,
              chance_of_rain: 100,
              will_it_snow: 1,
              chance_of_snow: 100,
              vis_km: 5,
              vis_miles: 3,
              gust_mph: 14,
              gust_kph: 22.6,
              uv: 0.2,
            },
            {
              time_epoch: 1767610800,
              time: "2026-01-05 13:00",
              temp_c: 0.2,
              temp_f: 32.4,
              is_day: 1,
              condition: {
                text: "Сильний сніг",
                icon: "//cdn.weatherapi.com/weather/64x64/day/338.png",
                code: 1225,
              },
              wind_mph: 8.7,
              wind_kph: 14,
              wind_degree: 77,
              wind_dir: "ENE",
              pressure_mb: 1020,
              pressure_in: 30.12,
              precip_mm: 0.34,
              precip_in: 0.01,
              snow_cm: 0.25,
              humidity: 97,
              cloud: 100,
              feelslike_c: -4,
              feelslike_f: 24.9,
              windchill_c: -4,
              windchill_f: 24.9,
              heatindex_c: 0.2,
              heatindex_f: 32.4,
              dewpoint_c: -0.3,
              dewpoint_f: 31.6,
              will_it_rain: 1,
              chance_of_rain: 100,
              will_it_snow: 1,
              chance_of_snow: 100,
              vis_km: 2,
              vis_miles: 1,
              gust_mph: 12.4,
              gust_kph: 19.9,
              uv: 0.2,
            },
            {
              time_epoch: 1767614400,
              time: "2026-01-05 14:00",
              temp_c: 0.6,
              temp_f: 33.1,
              is_day: 1,
              condition: {
                text: "Невеликий дощ зі снігом",
                icon: "//cdn.weatherapi.com/weather/64x64/day/317.png",
                code: 1204,
              },
              wind_mph: 11.2,
              wind_kph: 18,
              wind_degree: 75,
              wind_dir: "ENE",
              pressure_mb: 1019,
              pressure_in: 30.1,
              precip_mm: 0.25,
              precip_in: 0.01,
              snow_cm: 0,
              humidity: 97,
              cloud: 100,
              feelslike_c: -4.2,
              feelslike_f: 24.5,
              windchill_c: -4.2,
              windchill_f: 24.5,
              heatindex_c: 0.6,
              heatindex_f: 33.1,
              dewpoint_c: 0.2,
              dewpoint_f: 32.4,
              will_it_rain: 1,
              chance_of_rain: 100,
              will_it_snow: 1,
              chance_of_snow: 88,
              vis_km: 9,
              vis_miles: 5,
              gust_mph: 15.2,
              gust_kph: 24.4,
              uv: 0.1,
            },
            {
              time_epoch: 1767618000,
              time: "2026-01-05 15:00",
              temp_c: 1,
              temp_f: 33.8,
              is_day: 1,
              condition: {
                text: "Місцями дощ",
                icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
                code: 1063,
              },
              wind_mph: 11.2,
              wind_kph: 18,
              wind_degree: 76,
              wind_dir: "ENE",
              pressure_mb: 1019,
              pressure_in: 30.09,
              precip_mm: 0.12,
              precip_in: 0,
              snow_cm: 0,
              humidity: 97,
              cloud: 100,
              feelslike_c: -3.7,
              feelslike_f: 25.4,
              windchill_c: -3.7,
              windchill_f: 25.4,
              heatindex_c: 1,
              heatindex_f: 33.8,
              dewpoint_c: 0.6,
              dewpoint_f: 33.1,
              will_it_rain: 1,
              chance_of_rain: 100,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.7,
              gust_kph: 23.7,
              uv: 0.1,
            },
            {
              time_epoch: 1767621600,
              time: "2026-01-05 16:00",
              temp_c: 1.1,
              temp_f: 34.1,
              is_day: 1,
              condition: {
                text: "Місцями дощ",
                icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
                code: 1063,
              },
              wind_mph: 12.1,
              wind_kph: 19.4,
              wind_degree: 78,
              wind_dir: "ENE",
              pressure_mb: 1018,
              pressure_in: 30.07,
              precip_mm: 0.15,
              precip_in: 0.01,
              snow_cm: 0,
              humidity: 98,
              cloud: 100,
              feelslike_c: -3.7,
              feelslike_f: 25.3,
              windchill_c: -3.7,
              windchill_f: 25.3,
              heatindex_c: 1.1,
              heatindex_f: 34.1,
              dewpoint_c: 0.8,
              dewpoint_f: 33.5,
              will_it_rain: 1,
              chance_of_rain: 100,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 16.2,
              gust_kph: 26,
              uv: 0,
            },
            {
              time_epoch: 1767625200,
              time: "2026-01-05 17:00",
              temp_c: 1.3,
              temp_f: 34.4,
              is_day: 0,
              condition: {
                text: "Місцями дощ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
                code: 1063,
              },
              wind_mph: 12.3,
              wind_kph: 19.8,
              wind_degree: 78,
              wind_dir: "ENE",
              pressure_mb: 1018,
              pressure_in: 30.07,
              precip_mm: 0.08,
              precip_in: 0,
              snow_cm: 0,
              humidity: 98,
              cloud: 100,
              feelslike_c: -3.5,
              feelslike_f: 25.6,
              windchill_c: -3.5,
              windchill_f: 25.6,
              heatindex_c: 1.3,
              heatindex_f: 34.4,
              dewpoint_c: 1,
              dewpoint_f: 33.7,
              will_it_rain: 1,
              chance_of_rain: 100,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 16.7,
              gust_kph: 26.9,
              uv: 0,
            },
            {
              time_epoch: 1767628800,
              time: "2026-01-05 18:00",
              temp_c: 1.3,
              temp_f: 34.3,
              is_day: 0,
              condition: {
                text: "Місцями дощ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
                code: 1063,
              },
              wind_mph: 13,
              wind_kph: 20.9,
              wind_degree: 79,
              wind_dir: "E",
              pressure_mb: 1018,
              pressure_in: 30.05,
              precip_mm: 0.14,
              precip_in: 0.01,
              snow_cm: 0,
              humidity: 98,
              cloud: 100,
              feelslike_c: -3.8,
              feelslike_f: 25.3,
              windchill_c: -3.8,
              windchill_f: 25.3,
              heatindex_c: 1.3,
              heatindex_f: 34.3,
              dewpoint_c: 0.9,
              dewpoint_f: 33.7,
              will_it_rain: 1,
              chance_of_rain: 100,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 18.4,
              gust_kph: 29.6,
              uv: 0,
            },
            {
              time_epoch: 1767632400,
              time: "2026-01-05 19:00",
              temp_c: 1.3,
              temp_f: 34.4,
              is_day: 0,
              condition: {
                text: "Місцями дощ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
                code: 1063,
              },
              wind_mph: 13.2,
              wind_kph: 21.2,
              wind_degree: 82,
              wind_dir: "E",
              pressure_mb: 1017,
              pressure_in: 30.04,
              precip_mm: 0.02,
              precip_in: 0,
              snow_cm: 0,
              humidity: 97,
              cloud: 100,
              feelslike_c: -3.7,
              feelslike_f: 25.3,
              windchill_c: -3.7,
              windchill_f: 25.3,
              heatindex_c: 1.4,
              heatindex_f: 34.4,
              dewpoint_c: 1,
              dewpoint_f: 33.8,
              will_it_rain: 1,
              chance_of_rain: 81,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 19,
              gust_kph: 30.6,
              uv: 0,
            },
            {
              time_epoch: 1767636000,
              time: "2026-01-05 20:00",
              temp_c: 1.3,
              temp_f: 34.4,
              is_day: 0,
              condition: {
                text: "Суцільна хмарність",
                icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
                code: 1009,
              },
              wind_mph: 13.4,
              wind_kph: 21.6,
              wind_degree: 81,
              wind_dir: "E",
              pressure_mb: 1017,
              pressure_in: 30.02,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 98,
              cloud: 100,
              feelslike_c: -3.8,
              feelslike_f: 25.2,
              windchill_c: -3.8,
              windchill_f: 25.2,
              heatindex_c: 1.3,
              heatindex_f: 34.4,
              dewpoint_c: 1,
              dewpoint_f: 33.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 20.2,
              gust_kph: 32.4,
              uv: 0,
            },
            {
              time_epoch: 1767639600,
              time: "2026-01-05 21:00",
              temp_c: 1.4,
              temp_f: 34.5,
              is_day: 0,
              condition: {
                text: "Місцями дощ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
                code: 1063,
              },
              wind_mph: 13,
              wind_kph: 20.9,
              wind_degree: 80,
              wind_dir: "E",
              pressure_mb: 1016,
              pressure_in: 30,
              precip_mm: 0.06,
              precip_in: 0,
              snow_cm: 0,
              humidity: 98,
              cloud: 100,
              feelslike_c: -3.6,
              feelslike_f: 25.4,
              windchill_c: -3.6,
              windchill_f: 25.4,
              heatindex_c: 1.4,
              heatindex_f: 34.4,
              dewpoint_c: 1.1,
              dewpoint_f: 33.9,
              will_it_rain: 1,
              chance_of_rain: 100,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 20.1,
              gust_kph: 32.3,
              uv: 0,
            },
            {
              time_epoch: 1767643200,
              time: "2026-01-05 22:00",
              temp_c: 1.4,
              temp_f: 34.6,
              is_day: 0,
              condition: {
                text: "Невеликий дощ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/266.png",
                code: 1153,
              },
              wind_mph: 13.2,
              wind_kph: 21.2,
              wind_degree: 78,
              wind_dir: "ENE",
              pressure_mb: 1015,
              pressure_in: 29.98,
              precip_mm: 0.21,
              precip_in: 0.01,
              snow_cm: 0,
              humidity: 98,
              cloud: 100,
              feelslike_c: -3.6,
              feelslike_f: 25.5,
              windchill_c: -3.6,
              windchill_f: 25.5,
              heatindex_c: 1.4,
              heatindex_f: 34.6,
              dewpoint_c: 1.1,
              dewpoint_f: 34,
              will_it_rain: 1,
              chance_of_rain: 100,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 2,
              vis_miles: 1,
              gust_mph: 21,
              gust_kph: 33.8,
              uv: 0,
            },
            {
              time_epoch: 1767646800,
              time: "2026-01-05 23:00",
              temp_c: 1.6,
              temp_f: 34.8,
              is_day: 0,
              condition: {
                text: "Місцями дощ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
                code: 1063,
              },
              wind_mph: 13,
              wind_kph: 20.9,
              wind_degree: 79,
              wind_dir: "E",
              pressure_mb: 1015,
              pressure_in: 29.96,
              precip_mm: 0.1,
              precip_in: 0,
              snow_cm: 0,
              humidity: 98,
              cloud: 100,
              feelslike_c: -3.4,
              feelslike_f: 25.9,
              windchill_c: -3.4,
              windchill_f: 25.9,
              heatindex_c: 1.6,
              heatindex_f: 34.8,
              dewpoint_c: 1.3,
              dewpoint_f: 34.3,
              will_it_rain: 1,
              chance_of_rain: 100,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 21.7,
              gust_kph: 34.8,
              uv: 0,
            },
          ],
        },
      ],
    },
  };
  return (
    <>
      <Container>
        <div className="flex flex-1 flex-col gap-4 p-0 sm:p-4 w-full">
          <div className="flex flex-col items-center">
            <h1 className="text-3xl font-bold text-shadow">Роздільна</h1>
            <h2 className="text-7xl">14°</h2>
            <p className="text-lg text-muted-foreground text-shadow">
              Сонячно, відчувається як 19°
            </p>
            <div className="flex gap-4 text-lg text-shadow">
              <p>B:10°</p>
              <p>H:22°</p>
            </div>
          </div>
          <div className="">
            <div className="flex justify-between bg-muted/50 rounded-xl overflow-x-auto no-scrollbar">
              {data.forecast.forecastday[0].hour.slice(0, 24).map((hour) => (
                <div
                  key={hour.time}
                  className="flex flex-col items-center hover:bg-muted/70 rounded-xl text-shadow flex-shrink-0 py-3"
                >
                  <p className="text-sm font-medium">
                    {new Date(hour.time).getHours()}:00
                  </p>
                  <img
                    src={`https:${hour.condition.icon}`}
                    alt="Weather icon"
                    className="w-12 h-12"
                  />
                  <p className="text-lg font-semibold">
                    {Math.round(hour.temp_c)}°
                  </p>
                </div>
              ))}
            </div>
          </div>
          <div className="grid auto-rows-min gap-4 md:grid-cols-3">
            <div className="bg-muted/50 aspect-video rounded-xl" />
            <div className="bg-muted/50 aspect-video rounded-xl" />
            <div className="bg-muted/50 aspect-video rounded-xl" />
          </div>
        </div>
      </Container>
    </>
  );
}
